# Generated by Django 5.1.7 on 2025-03-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='tech_stack',
            new_name='all_tech_stack',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_link',
            new_name='application_link',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_title',
        ),
    ]
